# Generated by Django 3.2.4 on 2021-07-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('serie', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
